#!/usr/bin/env bash

set -e

pushd ~/code/nix-forge

[ -f ~/code/nix-forge/rc2nix.nix ] && rm ~/code/nix-forge/rc2nix.nix

rm -f "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json.bak"
rm -f "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json.bak"

find . -type f -name "*.nix" -exec git add {} +

yq -o=json secrets.yml > .secrets.json

export NIXPKGS_ALLOW_UNFREE=1

if [ "$(uname)" = "Darwin" ]; then
  #rm -f "$HOME/Library/Application Support/Code/User/settings.json"
  #rm -f "$HOME/Library/Application Support/Code/User/settings.json.bak"
  #sudo darwin-rebuild switch --flake .#traveller
  # -E and --impure needed to see the NIXPKGS_ALLOW_UNFREE env var
  sudo -E darwin-rebuild switch --impure --flake .#traveller
  #brew upgrade
  #move-aside "$HOME/Library/Application Support/Code/User/settings.json"
#elif [ "$(hostname)" = "mpro" ]; then
#  nh os switch .
else
  #sudo nixos-rebuild switch --flake .
  #sudo nixos-rebuild switch --flake . |& nom
  sudo -E nixos-rebuild switch --impure --flake .
  #rm -f "$HOME/.config/Code/User/settings.json"
  #rm -f "$HOME/.config/Code/User/settings.json.bak"
  # nh os switch .
  #move-aside "$HOME/.config/Code/User/settings.json"
  #nh os switch . -- --impure
fi

cp "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json" "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json.tmp"
cp "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json" "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json.tmp"
rm -f "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json"
rm -f "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json"
mv "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json.tmp" "/Users/connor.rhodes/Library/Application Support/Code/User/settings.json"
mv "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json.tmp" "/Users/connor.rhodes/Library/Application Support/Code/User/keybindings.json"

popd
