- key: "cmd+j"
  command: "-workbench.action.togglePanel"
- key: "cmd+j"
  command: "workbench.action.terminal.toggleTerminal"
  when: "terminal.active"
- key: "ctrl+`"
  command: "-workbench.action.terminal.toggleTerminal"
  when: "terminal.active"
